### ISSUE TITLE
SPI

### ISSUE THREAD

**Issue by codeofmichael** [LattePandaTeam/Docs#89]
Hi, 

i can't figure out how to solve the following issues:

1. how can i address the Header Pins from LP side (I2C, USB etc //without using Arduino of course)
2. how to use the Arduino SPI with my Visual Stduio Projekt in C#.
The provided Firmata are only supporting I2C if im reading correctly. Is there any upgraded Firmata for SPI available? 
Can you tell me, what i have to do to make it work?

**Comment by alphaarea** [comment]
1. USB can undoubtedly be used directly, but intel I2C currently does not have a convenient way to use. Generally speaking it will only be configured from the BIOS as an I2C HID device and used with a touch screen panel
2. Firmata is most of the time only worth for controlling simple digital and analog I/O. Even though the protocol documentation adds I2C and SPI support, UART-based Firmata is too slow for I2C and SPI.

For situations that require the use of SPI and I2C, I recommend using the USB interface extension FT232H series of chips (note is not FT232R). These chips are faster and more stable using USB communication and are supported by good development documentation.

- [FDTI Example](https://ftdichip.com/software-examples/code-examples/csharp-examples/)
- [D2XX Programmer’s Guide](https://ftdichip.com/wp-content/uploads/2020/08/D2XX_Programmers_GuideFT_000071.pdf)

**Comment by codeofmichael** [comment]
Thanks for your reply and 
But why would LP put a Header with lables of those Functionallty including i2c and i2s and promote their ready to use feature, when its basically not "usable"?

**Comment by alphaarea** [comment]
I2S is readily available for use. Once enabled, an Intel SST audio device will be visible within the system. Selecting it will output audio via I2S.

Indeed, utilizing the CPU I2C can prove to be quite challenging. This is typical of Intel's design philosophy, which differs significantly from that of the Raspberry Pi. The I2C is primarily intended for connecting fixed internal chips within a PC, rather than serving as a readily-developable external interface.
